// SPDX-License-Identifier: MIT
// SpatialDDS Common Type Aliases 1.0

#ifndef SPATIAL_COMMON_TYPES_INCLUDED
#define SPATIAL_COMMON_TYPES_INCLUDED

module spatial {
  module common {
    typedef double BBox2D[4];
    typedef double Aabb3D[6];
    typedef double QuaternionXYZW[4]; // (x,y,z,w)
    typedef double Vec3[3];
    typedef double Mat3x3[9];
    typedef double Mat6x6[36];
  };
};

#endif // SPATIAL_COMMON_TYPES_INCLUDED
